apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/admin/Desktop/k8s/k8s-resources/yaml_k8s_resources/volume/volumetest"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
