apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx: |
    server {
      listen 80;
      server_name my-nginx;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - name: nginx-vol
          mountPath: /etc/nginx/conf.d
  volumes:
    - name: nginx-vol
      configMap:
        name: nginx-config
        items:
          - key: nginx
            path: default.conf
